# Generated by Django 3.0.5 on 2020-04-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amazonurl', models.URLField()),
                ('amazonid', models.CharField(max_length=200)),
                ('amazonprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('walmarturl', models.URLField()),
                ('walmartid', models.CharField(max_length=200)),
                ('walmartprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('targeturl', models.URLField()),
                ('targetid', models.CharField(max_length=200)),
                ('targetprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowestprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loweststore', models.CharField(max_length=10)),
                ('historiclow', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
