# Generated by Django 3.0.5 on 2020-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamescrape', '0002_auto_20200502_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
