# Generated by Django 3.0.5 on 2020-05-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamescrape', '0003_auto_20200502_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
