# Generated by Django 3.0.5 on 2020-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamescrape', '0005_auto_20200503_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='amazonprice',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='historiclow',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='lowestprice',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='loweststore',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='lowesturl',
            field=models.URLField(default='amazon.com'),
        ),
        migrations.AlterField(
            model_name='game',
            name='walmartprice',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
